### ISSUE TITLE
Is this possible with other language?

### ISSUE THREAD

**Issue by yellowjs0304** [poloclub/unitable#5]
@ShengYun-Peng Hi, Thank you for sharing your amazing work.

while running your pipeline, I have some questions.
Does your model work with other languages? like Japanese, Chinese, Korean etc..

I think the "content.pt" model is the role of OCR. Is this right?

If I use the other OCR or PDF extractor like PDFParser, Is it can be applied to your pipeline?

**Comment by ShengYun-Peng** [comment]
Hi @yellowjs0304, thanks for your interest!

Yes, "content.pt" is used for OCR, i.e., table cell content recognition. I believe any OCR model that works for **multi-line text recognition** can be employed in UniTable's cell content branch. The beauty of UniTable lies in unifying all three tasks into one self-supervised training and inference pipeline, rather than combining existing methods from non-table domains.

**Comment by yellowjs0304** [comment]
Got it, Thank you.
